# name of the app
name: namer_app
description: A new Flutter project.

# publishing to nowhere
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

# Version of the dart SDK
environment:
  sdk: '>=2.19.4 <4.0.0'

# Dependencies required
dependencies:
  flutter:
    sdk: flutter
  
  # Packages
  english_words: ^4.0.0
  provider: ^6.0.0

# development/debug
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# flutter options
flutter:
  uses-material-design: true
