#!/bin/bash

mkdir ./AmicableTests
cp ./amNums.c ./AmicableTests
cp ./makefile ./AmicableTests

make -s -C ./AmicableTests

echo -en "Various test will be performed, all results will be in amtimes.t, in ./AmicableTests\n"

for i in {1..4}
do
    echo -en "; Results of $i Threads @ 1M numbers ----\n" >> amtimes.t
    { time ./AmicableTests/amNums -t $i -l 1000000 > /dev/null 2>&1 ; } 2>> amtimes.t
done

echo -en "Removing pthreads_mutex_(un)lock(s) from the program and recompiling in ./AmicableTests\n"

sed 's/\(\(.*\) pthread_mutex\(.*\)\)/\/\/\1/g' ./AmicableTests/amNums.c > ./AmicableTests/amNums2.c
mv ./AmicableTests/amNums.c ./AmicableTests/amNums.bac
mv ./AmicableTests/amNums2.c ./AmicableTests/amNums.c
make -s -C ./AmicableTests

for i in {1..4}
do
    echo -en "; Results of !NO-MUTEX! $i Threads @ 1M numbers ----\n" >> amtimes.t
    { time ./AmicableTests/amNums -t $i -l 1000000 > /dev/null 2>&1 ; } 2>> amtimes.t

done

echo -en "Restoring pthread_mutex_(un)lock(s) to the program and recompiling in ./AmicableTests\n"

mv ./AmicableTests/amNums.bac ./AmicableTests/amNums.c
make -s -C ./AmicableTests

for i in {1..4}
do
    echo -en "; Results of run '$i'; 64 Threads @ 1M numbers ----\n" >>  amtimes.t
    { time ./AmicableTests/amNums -t 64 -l 1000000 > /dev/null 2>&1 ; } 2>> amtimes.t

done

